- hosts: localhost
  gather_facts: false
  become: true
  vars:
    app_name: "{{ app_name }}"
    server_name: "{{ server_name }}"
    web_root: "/home/{{ ansible_user }}/{{ app_name }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Create web root directory
      file:
        path: "{{ web_root }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Setup permission for user home directory
      file:
        path: "/home/{{ ansible_user }}"
        mode: '0755'
        recurse: yes

    - name: Setup permissions for web root
      file:
        path: "{{ web_root }}"
        mode: '0755'
        recurse: yes

    - name: Configure NGINX
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}
      notify: test nginx config

    - name: Enable NGINX site
      file:
        src: /etc/nginx/sites-available/{{ app_name }}
        dest: /etc/nginx/sites-enabled/{{ app_name }}
        state: link
      notify: test nginx config

  handlers:
    - name: test nginx config
      command: nginx -t
      register: nginx_test_result
      failed_when: nginx_test_result.rc != 0
      notify: reload nginx

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      register: nginx_reload_result
      failed_when: nginx_reload_result is failed
