name: Build and Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  app_name: "{{ APP_NAME }}"
  SSH_KEY_FILE_NAME: "id_rsa"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Store SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ env.SSH_KEY_FILE_NAME }}

      - name: Change SSH key permission
        run: chmod 444 ${{ env.SSH_KEY_FILE_NAME }}

      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          source: "./dist/*"
          target: "/home/${{ secrets.SERVER_USER }}/{{ env.APP_NAME }}/"
