name: Server Setup

on:
  workflow_dispatch:
  push:
    paths:
      - "ansible/**"
      - "nginx.conf.j2"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ansible
        run:
          sudo apt update
          sudo apt install -y ansible

      - name: Upload Ansible playbook to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./ansible/*"
          target: "/home/${{ secrets.SERVER_USER }}/ansible/"

      - name: Trigger Ansible Playbook
        env:
          SSL_CERT: ${{ secrets.SSL_CERT }}
          SSL_KEY: ${{ secrets.SSL_KEY }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/ansible
            ansible-playbook -i "$SERVER_HOST," -u "$SERVER_USER" deploy.yml
