name: Server Setup

on:
  workflow_dispatch:
  push:
    paths:
      - "ansible/**"
      - "nginx.conf.j2"

env:
  SSH_KEY_FILE_NAME: "id_rsa"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Store SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ env.SSH_KEY_FILE_NAME }}

      - name: Change SSH key permission
        run: chmod 444 ${{ env.SSH_KEY_FILE_NAME }}

      - name: Upload Ansible playbook to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          port: ${{ secrets.SSH_PORT }}
          source: "ansible/playbook.yml"
          target: "/home/${{ secrets.SERVER_USER }}/"

      - name: Setup Ansible on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo apt update -y
            sudo apt install -y ansible

      - name: Trigger Ansible Playbook
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/ansible
            ansible-playbook -i "${{ secrets.SERVER_HOST }}," -u "${{ secrets.SERVER_USER }}" deploy.yml
